logging:
  level: TRACE
  loggers:
    com.akhilesh.learning: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: darwinadmin
  password: P@ssw0rd
  url: jdbc:postgresql://shemp-pg01.swinfra.net/db-users
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: create
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false